name: "Build"
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
# Uncomment for ssh
#   - name: Setup upterm session
#     uses: lhotari/action-upterm@v1
    - name: Run Tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: nix-shell --run "clojure -M:test"
    - name: Deploy Preview
      run: |
        git clean -fxd
        git config --global user.name "github-actions[bot]"
        git config --global user.email "noreply@visr.pl"
        date > src/injectable/date.inject
        nix-shell --run "clojure -M:package"
        rm -r node_modules
        cp public/index-loadingbar.html index.html
        echo "visr.pl" > CNAME
        git add -A -f
        git checkout -b preview
        git commit --allow-empty -m "** deploy visr/website@$GITHUB_SHA"
        git push origin preview -f
